/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class AllBusDetails extends javax.swing.JInternalFrame {
Connection con ;
ResultSet RS;
PreparedStatement pst;
   
    public AllBusDetails() {
        initComponents();
    }
    public ArrayList<User> userList(){
        ArrayList<User>userList =new ArrayList<>();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/bus";
            Connection con = DriverManager.getConnection(databaseURL, "sai123", "sai@saisaisa");
            String query1="select * FROM bus_details";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query1);
            User user;
            while(rs.next()){
                user=new User(rs.getInt("id"), rs.getString("bus_no"), rs.getString("movement"),rs.getString("bus_source"),rs.getString("bus_dest"),rs.getString("bus_date"),rs.getString("bus_time"),rs.getString("price"),rs.getString("total_seat"));
                userList.add(user);
            }
        }
        catch(ClassNotFoundException | SQLException e){
                        System.out.println(e);

        }
        return userList;
    }
    public void show_user(){
        ArrayList<User> list=userList();
       //
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getbus_no();
            row[2]=list.get(i).getmovement();
            row[3]=list.get(i).getbus_source();
            row[4]=list.get(i).getbus_dest();
            row[5]=list.get(i).getdepart_date();
            row[6]=list.get(i).getdepart_time();
            row[7]=list.get(i).getprice();
            row[8]=list.get(i).gettotal_seat();
            //
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bindingGroup1 = new org.jdesktop.beansbinding.BindingGroup();
        bindingGroup2 = new org.jdesktop.beansbinding.BindingGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JTable jTable_Display = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("All Bus Details");

        jTable_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Bus No", "Movement", "Bus Source", "Bus Dest", "Depart Date", "Price", "Total Seat"
            }
        ));
        jTable_Display.setShowGrid(true);
        jTable_Display.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(jTable_Display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.beansbinding.BindingGroup bindingGroup1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private static class jTable1 {

        private static void setModel(TableModel resultSetToTableModel) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public jTable1() {
        }
    }
}
